import AmbientLight from "../../lights/AmbientLight";

export const movableModels = [
  {
    name: 'book',
    filePath: '/models/book.glb',
    scale: .9,
    rotation: [0, 0, 0],
    height: 0.5,
    metallic: 0.3,
    roughness: 0.6,
    mass: 0.2,
    linearDamping: 0.3,
    angularDamping: 0.3,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1,
    collider: 'cuboid'
  },
  {
    name: 'bannana',
    filePath: '/models/bananna.glb',
    scale: .1,
    rotation: [0, 0, 0],
    height: 0.5,
    metallic: 0.01,
    roughness: 0.01,
    mass: 0.2,
    linearDamping: 0.3,
    angularDamping: 0.3,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'apple',
    filePath: '/models/apple.glb',
    scale: 0.01,
    rotation: [0, Math.PI / 4, 0],
    color: 'red',
    height: 0.5,
    metallic: 0.3,
    roughness: 0.6,
    mass: 0.2,
    linearDamping: 0.3,
    angularDamping: 0.3,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'alarmClock',
    filePath: '/models/AlarmClock+Texture.glb',
    scale: 0.1,
    rotation: [0, 0, 0],
    height: 0.3,
    roughness: 0.3,
    mass: 0.5,
    linearDamping: 0.5,
    angularDamping: 0.5,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'backpack',
    filePath: '/models/Backpack+Texture.glb',
    scale: 10,
    rotation: [0, Math.PI / 6, 0],
    height: 0.8,
    metallic: 0.1,
    roughness: 0.8,
    mass: 1,
    linearDamping: 0.6,
    angularDamping: 0.6,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'baseballGlove',
    filePath: '/models/baseballglove.glb',
    scale: 0.01,
    rotation: [0, Math.PI / 6, 0],
    height: 0.8,
    metallic: 0.1,
    roughness: 0.8,
    mass: 1,
    linearDamping: 0.6,
    angularDamping: 0.6,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'eyeglasses',
    filePath: '/models/eyeglasses.glb',
    scale: .1,
    height: 0.8,
    metallic: 0.1,
    roughness: 0.8,
    mass: 1,
    linearDamping: 0.6,
    angularDamping: 0.6,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'handbag',
    filePath: '/models/Purse+Texture.glb',
    scale: 7,
    rotation: [0, -Math.PI / 8, 0],
    color: 'red',
    height: 0.6,
    metallic: 0.2,
    roughness: 0.7,
    mass: 1.2,
    linearDamping: 0.4,
    angularDamping: 0.4,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'teddy',
    filePath: '/models/toyBear.glb',
    scale: .1,
    rotation: [0, Math.PI / 3, 0],
    height: 0.7,
    metallic: 0,
    roughness: 0.9,
    mass: 0.8,
    linearDamping: 0.7,
    angularDamping: 0.7,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'phone',
    filePath: '/models/phone.glb',
    scale: 3,
    rotation: [0, Math.PI / 2, 0],
    color: 'black',
    height: 0.2,
    metallic: 1,
    roughness: 0.1,
    mass: 0.3,
    linearDamping: 0.2,
    angularDamping: 0.2,
    castShadow: false,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'pottedPlant',
    filePath: '/models/pottedPlant.glb',
    scale: 5,
    rotation: [0, -Math.PI / 5, 0],
    height: 0.8,
    mass: 1.5,
    linearDamping: 0.5,
    angularDamping: 0.5,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'spoon',
    filePath: '/models/spoon.glb',
    scale: 0.015,
    rotation: [0, Math.PI / 4, 0],
    color: 'silver',
    height: 1,
    metallic: 0.3,
    roughness: 0.5,
    mass: 0.9,
    linearDamping: 0.4,
    angularDamping: 0.4,
    castShadow: true,
    receiveShadow: true,
    AmbientLight: 1
  },
  {
    name: 'umbrella',
    filePath: '/models/umbrella.glb',
    scale: 0.015,
    rotation: [0, Math.PI / 4, 0],
    color: 'red',
    height: 1,
    metallic: 0.3,
    roughness: 0.5,
    mass: 0.9,
    linearDamping: 0.4,
    angularDamping: 0.4,
    castShadow: true,
    receiveShadow: true,
    collider: 'ball'
  },
  // {
  //   name: 'book',
  //   filePath: '/models/Book.glb',
  //   scale: 0.4,
  //   rotation: [0, 0, 0],
  //   height: 0.3,
  //   metallic: 0.1,
  //   roughness: 0.9,
  //   mass: 0.6,
  //   linearDamping: 0.5,
  //   angularDamping: 0.5,
  //   castShadow: true,
  //   receiveShadow: true,
  // },
  {
    name: 'keys',
    filePath: '/models/keys1.glb',
    scale: 0.009,
    rotation: [0, -Math.PI / 6, 0],
    color: 'gold',
    height: 0.2,
    metallic: 1,
    roughness: 0.2,
    mass: 0.1,
    linearDamping: 0.1,
    angularDamping: 0.1,
    castShadow: false,
    receiveShadow: true,
    AmbientLight: 1
  }
];
